#!/bin/bash

RESULT_BUNDLE_PATH=result/StoreKitTestingExampleTests.xcresult
rm -r "$RESULT_BUNDLE_PATH"
mkdir -p result
log stream --predicate 'subsystem = "com.apple.appstored"' --level debug > result/StoreKitInXcode.log &
trap "kill -2 $!" EXIT
xcodebuild test \
    -project StoreKitTestingExample.xcodeproj \
    -scheme StoreKitTestingExample \
    -configuration Debug \
    -destination 'platform=iOS Simulator,name=iPhone 8' \
    -test-iterations 100 \
    -resultBundlePath "$RESULT_BUNDLE_PATH" \
    -only-testing StoreKitTestingExampleTests/StoreKitTestingExampleTests/testPurchase \
    -quiet \
    BUILD_DIR=build
